### ISSUE TITLE
binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by dreamyuchen** [yahoo/object_relation_transformer#13]
when I run code：
python scripts/make_bu_data.py
![image](https://user-images.githubusercontent.com/17546537/125047315-6b6ca100-e0d1-11eb-9b22-efc8c6c6db82.png)
how can I solve this problem.

**Comment by gsrivas4** [comment]
I have corrected the code to resolved the issue in the latest commit - https://github.com/yahoo/object_relation_transformer/commit/6cf5bd8b96e8388cad482af45dfae78348002c13.

**Comment by buproof** [comment]
![code](https://user-images.githubusercontent.com/109445058/194737564-ac627fe9-6e65-4ba4-aa00-9cb2892c7b66.PNG)
hello, I have corrected the code but I still have the issue，how can I solve this problem.
![错误](https://user-images.githubusercontent.com/109445058/194737573-5ab29609-1dd7-4db8-b8f7-d8112d69fed1.PNG)

**Comment by buproof** [comment]
hello, I have corrected the code but I still have the issue.Do you know how can I solve this problem.

![code](https://user-images.githubusercontent.com/109445058/194737679-2ac7dd59-3026-4316-8032-32c06227759e.PNG)
![错误](https://user-images.githubusercontent.com/109445058/194737689-61db7347-a62b-4318-8b55-30dcbb6f3baf.PNG)
